use QL_CB
go
-- CÂU 01
select NV.MANV, NV.TEN, NV.DCHI, NV.DTHOAI
from KHANANG KN join NHANVIEN NV on KN.MANV = NV.MANV
where KN.MALOAI = 'B747'
-- CÂU 02
select LB.MACB, LB.NGAYDI
from CHUYENBAY CB join LICHBAY LB on CB.MACB = LB.MACB
where CB.SBDI = 'DCA' and (CB.GIODI between '14:00' and '18:00')
-- CÂU 03
select distinct NV.TEN
from NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV join CHUYENBAY CB on PC.MACB = CB.MACB
where CB.MACB = '100' and CB.SBDI = 'SLC'
-- CÂU 04
select *
from CHUYENBAY CB join LICHBAY LB on CB.MACB = LB.MACB join MAYBAY MB on (LB.MALOAI = MB.MALOAI and LB.SOHIEU = MB.SOHIEU)
-- CÂU 05
select DC.MACB, DC.NGAYDI, KH.TEN, KH.DCHI, KH.DTHOAI
from KHACHHANG KH join DATCHO DC on KH.MAKH = DC.MAKH
order by DC.MACB asc, DC.NGAYDI desc
-- CÂU 06
select PC.MACB, PC.NGAYDI, NV.TEN, NV.DCHI, NV.DTHOAI
from PHANCONG PC join NHANVIEN NV on PC.MANV = NV.MANV
order by PC.MACB asc, PC.NGAYDI desc
-- CÂU 07
select PC.MACB, PC.NGAYDI, PC.MANV, NV.TEN
from NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV join CHUYENBAY CB on PC.MACB = CB.MACB
where CB.SBDEN = 'ORD'
-- CÂU 08
select PC.MACB, PC.NGAYDI, NV.TEN
from PHANCONG PC join NHANVIEN NV on PC.MANV = NV.MANV
where PC.MANV = '1001'
-- CÂU 09
select CB.MACB, CB.SBDI, CB.GIODI, CB.GIODEN, LB.NGAYDI
from CHUYENBAY CB join LICHBAY LB on CB.MACB = LB.MACB
where CB.SBDEN = 'DEN'
order by LB.NGAYDI desc, CB.SBDI asc
-- CÂU 10
select NV.TEN, LMB.HANGSX, LMB.MALOAI
from NHANVIEN NV join KHANANG KN on NV.MANV = KN.MANV join LOAIMB LMB on KN.MALOAI = LMB.MALOAI
-- CÂU 11
select NV.MANV, NV.TEN
from NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
where PC.MACB = '100' and PC.NGAYDI = '11/01/2000'
-- CÂU 12
select CB.MACB, NV.MANV, NV.TEN
from NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV join CHUYENBAY CB on PC.MACB = CB.MACB
where PC.NGAYDI = '10/31/2000' and CB.SBDI = 'MIA' and CB.GIODI = '20:30'
-- CÂU 13
select distinct PC.MACB, MB.SOHIEU, MB.MALOAI, LMB.HANGSX
from NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV join KHANANG KN on NV.MANV = KN.MANV join LOAIMB LMB on KN.MALOAI = LMB.MALOAI
join MAYBAY MB on LMB.MALOAI = MB.MALOAI
where NV.TEN = 'Quang'
-- CÂU 14
select NV.TEN
from NHANVIEN NV 
except
select NV.TEN
from NHANVIEN NV join PHANCONG PC on NV.MANV = PC.MANV
-- CÂU 15
select distinct KH.TEN
from KHACHHANG KH join DATCHO DC on KH.MAKH = DC.MAKH join LICHBAY LB on DC.MACB = LB.MACB join LOAIMB LMB on LB.MALOAI = LMB.MALOAI
where LMB.HANGSX = 'Boeing'
-- CÂU 16
select distinct CB.MACB
from CHUYENBAY CB join LICHBAY LB on CB.MACB = LB.MACB join MAYBAY MB on (LB.SOHIEU = MB.SOHIEU and LB.MALOAI = MB.MALOAI)
where MB.SOHIEU = 10 and MB.MALOAI = 'B747'

