
--1/ TRUY VAN LONG: SU DUNG TRUY VAN TRONG MENH DE MOT CAU TRUY VAN KHAC
--TRUY VAN LONG O SELECT
SELECT BM.MABM, BM.TENBM, (SELECT COUNT(*) FROM GIAOVIEN WHERE MABM = 'HTTT') AS SLGV
FROM BOMON BM
WHERE BM.MABM = 'HTTT'

--TRUY VAN LONG O FROM
SELECT BM.MABM, BM.TENBM, KQ.SLGV
FROM BOMON BM, (SELECT MABM, COUNT(*) AS SLGV FROM GIAOVIEN GROUP BY MABM) AS KQ
WHERE BM.MABM = 'HTTT' AND BM.MABM = KQ.MABM

--TRUY VAN LONG O WHERE
SELECT *
FROM GIAOVIEN
WHERE MAGV IN (SELECT MAGV FROM THAMGIADT WHERE MADT = '002')

--2/ TRUY VAN LONG VOI TOAN TU: (NOT) IN, ALL, ANY/SOME, TOAN TU SO SANH (=, >, <, ...)
--CU PHAP: TT_Y [IN | >= | <ANY | >=ALL | ...] (SELECT TT_X FROM ...)
--TT_Y VA TT_X PHAI TUONG DONG VE KIEU DU LIEU VA NGU NGHIA ==> TRUY VAN CON KHONG DUOC SELECT *
--luong >= all (select luong ...); luong = (select max(luong) from ..
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG >= 
	(SELECT GV2.LUONG FROM GIAOVIEN GV2 
	 WHERE GV2.MAGV='004' AND GV2.MAGV != GV.MAGV)

SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG >= ANY
	(SELECT GV2.LUONG FROM GIAOVIEN GV2 
	 WHERE GV2.MAGV='004' AND GV2.MAGV != GV.MAGV)

SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL
	(SELECT GV2.LUONG FROM GIAOVIEN GV2)

SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG = 
	(SELECT max(LUONG) FROM GIAOVIEN)


--3/ TRUY VAN LONG VOI (NOT) EXISTS ==> KIEM TRA (KHONG) TON TAI: TRUE KHI CO IT NHAT 1 DONG DU LIEU TRA RA
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS
	(SELECT * FROM GIAOVIEN GV2 --KIEM TRA TON TAI KHONG CAN QUAN TAM COT THUOC TINH TRA RA 
	 WHERE GV2.LUONG > GV.LUONG)


--4/ VI DU:
/****VD1: TIM THONG TIN GIAOVIEN KHONG CO QUAN LY CHUYEN MON GIAO VIEN KHAC****/
--CACH 1: DUNG EXISTS
select * from giaovien gv
where not exists (select gv2.GVQLCM from giaovien gv2 where gv2.gvqlcm = gv.MAGV)--long tuong quan


--CACH 2: DUNG IN
select * from giaovien gv
where gv.magv not in (select DISTINCT gv2.GVQLCM from giaovien gv2 where gv2.gvqlcm is not null)--long phan cap

--GV.MAGV NOT IN (001, 002, 004, OO7) -- MAGV == NULL

/****VD2: TIM MA VA HO TEN GIAOVIEN LA TRUONG KHOA CUA KHOA DONG GIAO VIEN NHAT****/
SELECT TR.MAGV, TR.HOTEN, COUNT(GV.MAGV) 
FROM GIAOVIEN TR, KHOA K, GIAOVIEN GV, BOMON BM
WHERE TR.MAGV = K.TRUONGKHOA AND K.MAKHOA = BM.MAKHOA AND GV.MABM = BM.MABM
GROUP BY TR.MAGV, TR.HOTEN
HAVING COUNT(*) >= ALL (
			SELECT COUNT(*) 
			FROM GIAOVIEN GV, BOMON BM
			WHERE GV.MABM = BM.MABM
			GROUP BY BM.MAKHOA)


/****VD3: TIM MA VA HO TEN GIAO VIEN THAM GIA NHIEU DE TAI NHAT****/
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) >= ALL (
--TRUY VAN CON: XUAT DS SL DE TAI TUNG GV THAM GIA
		SELECT COUNT(DISTINCT TG.MADT)
		FROM THAMGIADT TG
		GROUP BY TG.MAGV)
